SELECT DISTINCT    count(STNC_NON_COURSE), STNC_NON_COURSE , STNC_SCORE
FROM COLL_PRODUCTION.STUDENT_NON_COURSES where substr(STNC_NON_COURSE,3,4)='ACUP'
 and substr(STNC_NON_COURSE,8,1) in ('W','R') group by STNC_NON_COURSE, STNC_SCORE;
