SELECT DISTINCT   STNC_PERSON_ID,  STNC_NON_COURSE, STNC_TITLE, STNC_CATEGORY,, STNC_SCORE
FROM COLL_PRODUCTION.STUDENT_NON_COURSES where substr(STNC_NON_COURSE,3,4)='ACUP'
 and substr(STNC_NON_COURSE,8,1)='M';
