
#' ISD
#'
#' @param High_School Character. A the high schools to get ISDs for.
#'
#' @return a \code{data.frame} with the variables \code{ISD}, \code{Include_ISD}, \code{Include_ALL}, \code{Service_Area}, and \code{Service_Area_with_Private_Charter}

#' @export
#'
isd = function(High_School){


	ISD = dplyr::case_when(
		High_School == "ARLINGTON HIGH SCHOOL" ~ "Arlington ISD",
		High_School == "ARLINGTON COLLEGIATE HS" ~ "Arlington ISD",
		High_School == "AZLE HIGH SCHOOL" ~ "Azle ISD",
		High_School == "C F BREWER HIGH SCHOOL" ~ "White Settlement ISD",
		High_School == "CENTRAL HIGH SCHOOL" ~ "Keller ISD",
		High_School == "CROWLEY HIGH SCHOOL" ~ "Crowley ISD",
		High_School == "FAITH CHRISTIAN SCHOOL" ~ "zUnknown ISD",
		High_School == "FELLOWSHIP ACADEMY" ~ "zUnknown ISD",
		High_School == "FOSSIL RIDGE HIGH SCHOOL" ~ "Keller ISD",
		High_School == "HARMONY SCIENCE ACADEMY" ~ "zUnknown ISD",
		High_School == "JAMES BOWIE HIGH SCHOOL" ~ "Arlington ISD",
		High_School == "JAMES W MARTIN HIGH SCHOOL" ~ "Arlington ISD",
		High_School == "JUAN SEGUIN HIGH SCHOOL" ~ "Arlington ISD",
		High_School == "KELLER HIGH SCHOOL" ~ "Keller ISD",
		High_School == "KENNEDALE HIGH SCHOOL" ~ "Kennedale ISD",
		High_School == "LAMAR HIGH SCHOOL" ~ "Arlington ISD",
		High_School == "MANSFIELD LEGACY HIGH SCHOOL" ~ "Mansfield ISD",
		High_School == "Multiple High Schools" ~ "zUnknown ISD",
		High_School == "No High School" ~ "zUnknown ISD",
		High_School == "NORTH CROWLEY HIGH SCHOOL" ~ "Crowley ISD",
		High_School == "NORTH SIDE HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "SAM HOUSTON HIGH SCHOOL" ~ "Arlington ISD",
		High_School == "TEXAS ACADEMY BIOMEDICAL SCIENCES" ~ "Fort Worth ISD",
		High_School == "TEXAS ACADEMY MATH SCIENCE" ~ "zUnknown ISD",
		High_School == "TEXAS Unknown CEEB CODE" ~ "zUnknown ISD",
		High_School == "TIMBER CREEK HIGH SCHOOL" ~ "Keller ISD",
		High_School == "W E BOSWELL HIGH SCHOOL" ~ "Eagle Mountain Saginaw ISD",
		High_School == "SAGINAW HIGH SCHOOL" ~ "Eagle Mountain Saginaw ISD",
		High_School == "FELLOWSHIP CHRISTIAN ACADEMY" ~ "zUnknown ISD",
		High_School == "OUT STATE HIGH SCHOOL" ~ "zUnknown ISD",
		High_School == "HALTOM HIGH SCHOOL" ~ "Birdville ISD",



		High_School == "BIRDVILLE HIGH SCHOOL" ~  "Birdville ISD",
		High_School == "CARROLL SENIOR HIGH SCHOOL" ~ "Carroll ISD",
		High_School == "GRAPEVINE-COLLEYVILLE COLLEGIATE ACADEMY" ~ "Grapevine Colleyville ISD",
		High_School == "COLLEYVILLE HERITAGE HIGH SCHOOL" ~ "Grapevine Colleyville ISD",
		High_School == "DIAMOND HILL-JARVIS HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "FORT WORTH CHRISTIAN HIGH SCHOOL" ~ "zUnknown ISD",
		High_School == "FRONTIER HIGH SCHOOL" ~ "Mansfield ISD",
		High_School == "GRAPEVINE SENIOR HIGH SCHOOL" ~ "Grapevine Colleyville ISD",
		High_School == "LAWRENCE D BELL HIGH SCHOOL" ~ "Hurst Euless Bedford ISD",
		High_School == "MANSFIELD HIGH SCHOOL" ~ "Mansfield ISD",
		High_School == "MANSFIELD LAKE RIDGE HIGH SCHOOL" ~ "Mansfield ISD",
		High_School == "MANSFIELD SUMMIT HIGH SCHOOL" ~ "Mansfield ISD",
		High_School == "MANSFIELD TIMBERVIEW HIGH SCHOOL" ~ "Mansfield ISD",
		High_School == "POLYTECHNIC HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "RICHLAND SR HIGH SCHOOL" ~ "Birdville ISD",
		High_School == "ROBERT L PASCHAL HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "TRIMBLE TECHNICAL HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "TRINITY HIGH SCHOOL" ~ "Hurst Euless Bedford ISD",

		High_School == "O D WYATT SENIOR HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "SOUTH HILLS HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "SOUTHWEST HIGH SCHOOL" ~ "Fort Worth ISD",

		High_School == "TEXAS HOME SCHOOL HS" ~ "zUnknown ISD",
		High_School == "TEXAS VIRTUAL ACADEMY" ~ "zUnknown ISD",

		High_School == "ALTERNATIVE EDUCATION CENTER" ~ "zUnknown ISD",
		High_School == "ARLINGTON HEIGHTS CHRISTIAN ACADEM" ~ "zUnknown ISD",
		High_School == "BOWIE HIGH SCHOOL" ~ "zUnknown ISD",
		High_School == "CASTLEBERRY HIGH SCHOOL" ~ "Castleberry ISD",
		High_School == "DUNBAR HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "EVERMAN JOE C BEAN HIGH SCHOOL" ~ "Everman ISD",
		High_School == "AMON CARTER-RIVERSIDE HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "ARLINGTON HEIGHTS HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "CHISHOLM TRAIL HIGH SCHOOL" ~ "Eagle Mountain Saginaw ISD",
		High_School == "COPPELL SENIOR HIGH SCHOOL" ~ "Coppell ISD",
		High_School == "EASTERN HILLS HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "LAKE WORTH HIGH SCHOOL" ~ "Lake Worth ISD",
		High_School == "BURLESON HIGH SCHOOL" ~ "Burleson ISD",
		High_School == "JOSHUA HIGH SCHOOL" ~ "Joshua ISD",
		High_School == "WESTERN HILLS HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "L V BERKNER HIGH SCHOOL" ~ "Richardson ISD",
		High_School == "FWISD MARINE CREEK COLLEGIATE HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "A MACEO SMITH HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "BYRON NELSON HIGH SCHOOL" ~ "Northwest ISD",
		High_School == "JOHN DUBISKI CAREER HIGH SCHOOL" ~ "Grand Prairie ISD",
		High_School == "NORTHWEST HIGH SCHOOL" ~ "Northwest ISD",
		High_School == "SOUTH GRAND PRAIRIE HIGH SCHOOL" ~ "Grand Prairie ISD",
		High_School == "KENNEDALE ISD" ~ "Kennedale ISD",
		High_School == "ALEDO HIGH SCHOOL" ~ "Aledo ISD",
		High_School == "GRAND PRAIRIE HIGH SCHOOL" ~ "Grand Prairie ISD",
		High_School == "BURLESON CENTENNIAL HIGH SCHOOL" ~ "Burleson ISD",
		High_School == "MIDLOTHIAN HIGH SCHOOL" ~ "Midlothian ISD",
		High_School == "WEATHERFORD HIGH SCHOOL" ~ "Weatherford ISD",
		High_School == "CEDAR HILL HS" ~ "Cedar Hill ISD",
		High_School == "DUNCANVILLE HIGH SCHOOL" ~ "Duncanville ISD",
		High_School == "SUNSET HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "PLANO EAST SR HIGH SCHOOL" ~ "Plano ISD",
		High_School == "FLOWER MOUND HIGH SCHOOL" ~ "Lewisville ISD",
		High_School == "LAKEVIEW CENTENNIAL HIGH SCH" ~ "Garland ISD",
		High_School == "NORTHSIDE HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "JOHN H GUYER HIGH SCHOOL" ~ "Denton ISD",
		High_School == "NORTH MESQUITE HIGH SCHOOL" ~ "Mesquite ISD",
		High_School == "RICHARDSON HIGH SCHOOL" ~ "Richardson ISD",
		High_School == "JAMES M STEELE HIGH SCHOOL" ~ "Northwest ISD",
		High_School == "LINCOLN HUMANITIES-COMMUNCATIONS" ~ "Dallas ISD",
		High_School == "EDWARD S MARCUS HIGH SCHOOL" ~ "Lewisville ISD",
		High_School == "FRANKLIN D ROOSEVELT HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "NORTH GARLAND HIGH SCHOOL" ~ "Garland ISD",
		High_School == "PLANO SR HIGH SCHOOL" ~ "Plano ISD",
		High_School == "BILLY C RYAN HIGH SCHOOL" ~ "Denton ISD",
		High_School == "DENTON HIGH SCHOOL" ~ "Denton ISD",
		High_School == "B T WASHINGTON HS PERFORM VISUAL" ~ "Dallas ISD",
		High_School == "JAMES MADISON HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "WARREN T WHITE HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "HILLCREST HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "PLANO WEST SR HIGH SCHOOL" ~ "Plano ISD",
		High_School == "R L TURNER HIGH SCHOOL" ~ "Carrollton Farmers Branch ISD ",
		High_School == "SACHSE HIGH SCHOOL" ~ "Garland ISD",
		High_School == "THOMAS JEFFERSON HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "W W SAMUELL HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "LAKE DALLAS HIGH SCHOOL" ~ "Lake Dallas ISD",
		High_School == "CREEKVIEW HIGH SCHOOL" ~ "Carrollton Farmers Branch ISD ",
		High_School == "H GRADY SPRUCE HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "LAKE HIGHLANDS HIGH SCHOOL" ~ "Richardson ISD",
		High_School == "MESQUITE HIGH SCHOOL" ~ "Mesquite ISD",
		High_School == "ROCKWALL HEATH HIGH SCHOOL" ~ "Rockwall ISD",
		High_School == "ROCKWALL HIGH SCHOOL" ~ "Rockwall ISD",
		High_School == "L G PINKSTON HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "NAAMAN FOREST HIGH SCHOOL" ~ "Garland ISD",
		High_School == "POTEET HIGH SCHOOL" ~ "Mesquite ISD",
		High_School == "SOUTH GARLAND HIGH SCHOOL" ~ "Garland ISD",
		High_School == "WEST MESQUITE HIGH SCHOOL" ~ "Mesquite ISD",
		High_School == "BRYAN ADAMS HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "FRED MOORE HIGH SCHOOL" ~ "Denton ISD",
		High_School == "HEBRON HIGH SCHOOL" ~ "Lewisville ISD",
		High_School == "NORTH DALLAS HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "FRISCO HIGH SCHOOL" ~ "Frisco ISD",
		High_School == "DR JUSTIN WAKELAND HIGH SCHOOL" ~ "Frisco ISD",
		High_School == "LIBERTY HIGH SCHOOL" ~ "Frisco ISD",
		High_School == "CENTENNIAL HIGH SCHOOL" ~ "Frisco ISD",
		High_School == "WOODROW WILSON HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "W H ADAMSON HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "BOOKER T WASHINGTON SENIOR HIGH S" ~ "Dallas ISD",
		High_School == "GARLAND HIGH SCHOOL" ~ "Garland ISD",
		High_School == "MESA HIGH SCHOOL" ~ "White Settlement ISD",
		High_School == "CROSSROADS HIGH SCHOOL" ~ "Burleson ISD",
		High_School == "NIMITZ HIGH SCHOOL" ~ "Irving ISD",
		High_School == "MACARTHUR HIGH SCHOOL" ~ "Irving ISD",
		High_School == "IRVING HIGH SCHOOL" ~ "Irving ISD",
		High_School == "SKYLINE HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "VENTURE ALTERNATIVE HIGH SCHOOL" ~ "Arlington ISD",
		High_School == "NEW LIVES SCHOOL" ~ "Fort Worth ISD",
		High_School == "LEWISVILLE HIGH SCHOOL" ~ "Lewisville ISD",
		High_School == "SOUTH OAK CLIFF HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "DAVID W CARTER HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "JUSTIN F KIMBALL HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "REACH HIGH SCHOOL" ~ "Castleberry ISD",
		High_School == "WATSON LEARNING CENTER" ~ "Eagle Mountain Saginaw ISD",
		High_School == "EVERMAN ACADEMY HIGH SCHOOL" ~ "Everman ISD",
		High_School == "CROWLEY COLLEGIATE ACADEMY" ~ "Crowley ISD",
		High_School == "TCC SO/FWISD COLLEGIATE HS" ~ "Fort Worth ISD",
		High_School == "EVERMAN COLLEGIATE HIGH SCHOOL" ~ "Everman ISD",
		High_School == "MANSFIELD COLLEGIATE HS IN TIMBERVIEW HS" ~ "Mansfield ISD",
		High_School == "CLEBURNE HS" ~ "Cleburne ISD",
		High_School == "BENBROOK MIDDLE/HIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "BENBROOK MIDDLEHIGH SCHOOL" ~ "Fort Worth ISD",
		High_School == "YOUNG MENS LEADERSHIP ACADEMY" ~ "Fort Worth ISD",
		High_School == "YOUNG WOMENS LEADERSHIP ACADEMY" ~ "Fort Worth ISD",
		High_School ==  "FWISD MARINE CREEK COLLEGIATE HIGH SCHOOL" ~  "Fort Worth ISD",
		High_School == "V R EATON HIGH SCHOOL" ~ "Northwest ISD",
		High_School == "ALVARADO HIGH SCHOOL" ~ "Alvarado ISD",
		High_School == "ALL SAINTS EPISCOPAL SCHOOL" ~ "yPrivate/Charter",
		High_School == "HARMONY SCIENCE ACADEMY" ~ "yPrivate/Charter",
		High_School == "NOLAN CATHOLIC HIGH SCHOOL" ~ "yPrivate/Charter",
		High_School == "WINFREE ACADEMY HIGH SCHOOL" ~ "yPrivate/Charter",
		High_School == "INTERNATIONAL LEADERSHIP TEXAS KELLER HS" ~ "yPrivate/Charter",
		High_School == "HARMONY SCHOOL INNOVATION" ~ "yPrivate/Charter",
		High_School == "FELLOWSHIP ACADEMY" ~ "yPrivate/Charter",
		High_School == "IL TEXAS ARLINGTON-GRAND PRAIRIE HS" ~ "yPrivate/Charter",
		High_School == "CASSATA HIGH SCHOOL" ~ "yPrivate/Charter",
		High_School == "FAITH CHRISTIAN SCHOOL" ~ "yPrivate/Charter",
		High_School == "FORT WORTH CHRISTIAN HIGH SCHOOL" ~ "yPrivate/Charter",
		High_School == "CHISHOLM TRAIL ACADEMY" ~ "yPrivate/Charter",
		High_School == "BOWIE HIGH SCHOOL" ~ "El Paso ISD",
		High_School == "SEGUIN HIGH SCHOOL" ~ "Seguin ISD",
		High_School == "NAZARENE CHRISTIAN ACADEMY" ~ "yPrivate/Charter",
		High_School ==  'NORTHSIDE HIGH SCHOOL' ~ 'Houston ISD',
		High_School ==  'I M TERRELL HS' ~ 'Fort Worth ISD',
		High_School ==  'COLLEGIATE ACADEMY AT O, D, WYATT HIGH SCHOOL' ~ 'Fort Worth ISD',
		High_School ==  'AISD ARLINGTON COLLEGE CAREER HIGH SCHOOL' ~ 'Arlington ISD',
		High_School ==  'SUCCESS HIGH SCHOOL' ~ 'Fort Worth ISD',
		High_School ==  'VENUS HIGH SCHOOL' ~ 'Venus ISD',
		High_School ==  'SPRINGTOWN HIGH SCHOOL' ~ 'Springtown ISD',
		High_School ==  'GRANBURY SENIOR HIGH SCHOOL' ~ 'Granbury ISD',
		High_School ==  'GODLEY SENIOR HIGH SCHOOL' ~ 'Godley ISD',
		High_School ==  'DESOTO HIGH SCHOOL' ~ 'DeSoto ISD',
		High_School ==  'BOYD HIGH SCHOOL' ~ 'Boyd ISD',
		High_School ==  'ROBERT E LEE HIGH SCHOOL' ~ 'Tyler ISD',
		High_School ==  'WAXAHACHIE HIGH SCHOOL' ~ 'Waxahachie ISD',
		High_School ==  'DECATUR HIGH SCHOOL' ~ 'Decatur ISD',
		High_School ==  'RED OAK HIGH SCHOOL' ~ 'Red Oak ISD',
		High_School ==  'LANCASTER HIGH SCHOOL' ~ 'Lancaster ISD',
		High_School ==  'MINERAL WELLS HIGH SCHOOL' ~ 'Mineral Wells ISD',
		High_School ==  'ALLEN HIGH SCHOOL' ~ 'Allen ISD',
		High_School ==  'MOLINA HIGH SCHOOL' ~ 'Dallas ISD',
		High_School ==  'LINCOLN HUMANITIES-COMMUNCATIONS HIGH SCHOOL' ~ 'Dallas ISD',
		High_School ==  'LONGVIEW HIGH SCHOOL' ~ 'Longview ISD',
		High_School ==  'CROSSWINDS HIGH SCHOOL' ~ 'Grand Prairie ISD',
		High_School ==  'AMARILLO HIGH SCHOOL' ~ 'Amarillo ISD',
		High_School ==  'ALVORD HIGH SCHOOL' ~ 'Alvord ISD',
		High_School ==  'ALAMO HEIGHTS HIGH SCHOOL' ~ 'Alamo Heights ISD',
		High_School ==  'ANNA HEIGHTS HIGH SCHOOL' ~ 'Anna ISD',
		High_School ==  'ANNE MANSFIELD SULLIVAN H S' ~ 'Lake Worth ISD',
		High_School ==  'BEL AIR HIGH SCHOOL' ~ 'Ysleta ISD',
		High_School ==  'BELLAIRE HIGH SCHOOL' ~ 'Houston ISD',
		High_School ==  'BIG SPRING HIGH SCHOOL' ~ 'Big Spring ISD',
		High_School ==  'BISHOP DUNNE HIGH SCHOOL' ~ 'yPrivate/Charter',
		High_School ==  'BRIDGEPORT HIGH SCHOOL' ~ 'Bridgeport ISD',
		High_School ==  'CAPROCK HIGH SCHOOL' ~ 'Amarillo ISD',
		High_School ==  'CORSICANA HIGH SCHOOL' ~ 'Corsicana ISD',
		High_School ==  'ABILENE HIGH SCHOOL' ~ 'Abilene ISD',
		High_School ==  'A N MCCALLUM HIGH SCHOOL' ~ 'Austin ISD',
		High_School ==  'A M CONSOLIDATED HIGH SCHOOL' ~ 'College Station ISD',
		High_School ==  'ACADEMY IRVING ISD' ~ 'Irving ISD',
		High_School ==  'ALIEF HASTINGS HIGH SCHOOL' ~ 'Alief ISD',
		High_School ==  'ALIEF TAYLOR HIGH SCHOOL' ~ 'Alief ISD',
		High_School ==  'ANDRESS HIGH SCHOOL' ~ 'El Paso ISD',
		High_School ==  'ANNA HIGH SCHOOL' ~ 'Anna ISD',
		High_School ==  'ARGYLE HIGH SCHOOL' ~ 'Argyle ISD',
		High_School ==  'AUBREY HIGH SCHOOL' ~ 'Aubrey ISD',
		High_School ==  'B T WASHINGTON HS PERFORM VISUAL ARTS' ~ 'Dallas ISD',
		High_School ==  'BALL HIGH SCHOOL' ~ 'Galveston ISD',
		High_School ==  'BELTON HIGH SCHOOL' ~ 'Belton ISD',
		High_School == "BETHESDA CHRISTIAN SCHOOL" ~ "yPrivate/Charter",
		High_School == "AZLE CHRISTIAN SCHOOL" ~ "yPrivate/Charter",
		High_School == "AMERICAS NATIONAL CHRISTIAN ACADEMY" ~ "yPrivate/Charter",
		High_School == "AMERICAS HIGH SCHOOL" ~ "Socorro ISD",
		High_School == "WYLIE HIGH SCHOOL" ~ "Wylie ISD",
		High_School == "WILMER-HUTCHINS HIGH SCHOOL" ~ "Dallas ISD",
		High_School == "WILLS POINT HIGH SCHOOL" ~ "Wills Point ISD",
		High_School == "WILLIAM HOWARD TAFT HIGH SCHOOL" ~ "Northside ISD",
		High_School == "WILLIAM B TRAVIS HIGH SCHOOL" ~ "Austin ISD",
		High_School == "WICHITA FALLS HIGH SCHOOL" ~ "Wichita Falls ISD",
		High_School == "WHITNEY HIGH SCHOOL" ~ "Whitney ISD",
		High_School == "WHITEHOUSE HIGH SCHOOL" ~ "Whitehouse ISD",
		High_School == "WESTWOOD HIGH SCHOOL" ~ "Round Rock ISD",
		High_School == "WESTFIELD HIGH SCHOOL" ~ "Spring ISD",
		High_School == "WEST BROOK SENIOR HIGH SCHOOL" ~ "Beaumont ISD",
		High_School == "WANDA R SMITH HIGH SCHOOL" ~ "Keene ISD",
		High_School == "WACO HIGH SCHOOL" ~ "Waco ISD",
		High_School == "W B RAY HIGH SCHOOL" ~ "Corpus Christi ISD",
		High_School == "VALLEY VIEW HIGH SCHOOL" ~ "Valley View ISD",
		High_School == "TRINITY VALLEY SCHOOL" ~ "yPrivate/Charter",
		High_School == "TOMBALL HIGH SCHOOL" ~ "Tomball ISD",
		High_School == "TOM CLARK HIGH SCHOOL" ~ "Northside ISD",
		High_School == "THEODORE ROOSEVELT HIGH SCHOOL" ~ "North East ISD",
		High_School == "TERRELL HIGH SCHOOL" ~ "Terrell ISD",
		High_School == "TATUM HIGH SCHOOL" ~ "Tatum ISD",
		High_School == "TASCOSA HIGH SCHOOL" ~ "Amarillo ISD",
		High_School == "SULPHUR SPRINGS HIGH SCHOOL" ~ "Sulphur Springs ISD",
		High_School == "STEPHENVILLE HIGH SCHOOL" ~ "Stephenville ISD",
		High_School == "BRIDGEPORT HS" ~ "Bridgeport ISD",
		High_School == "BROWNSVILLE PORTER HIGH SCHOOL" ~ "Brownsville ISD",
		High_School == "BROWNWOOD HIGH SCHOOL" ~ "Brownwood ISD",
		High_School == "BROWNSBORO HIGH SCHOOL" ~ "Brownsboro ISD",
		High_School == "BRUCEVILLE-EDDY HIGH SCHOOL" ~ "Bruceville-Eddy ISD",
		High_School == "BRYAN HIGH SCHOOL" ~ "Bryan ISD",
		High_School == "BURKBURNETT HIGH SCHOOL" ~ "Burkburnett ISD",
		High_School == "C E ELLISON HIGH SCHOOL" ~ "Killeen ISD",
		High_School == "CALALLEN HIGH SCHOOL" ~ "Calallen ISD",
		High_School == "CHAPEL HILL HIGH SCHOOL" ~ "Chapel Hill ISD",
		High_School == "CHICO HIGH SCHOOL" ~ "Chico ISD",
		High_School == "CHISUM HIGH SCHOOL" ~ "Chisum ISD",
		High_School == "CINCO RANCH HIGH SCHOOL" ~ "Katy ISD",
		High_School == "CLEAR BROOK HIGH SCHOOL" ~ "Clear Creek ISD",
		High_School == "CLEAR CREEK HIGH SCHOOL" ~ "Clear Creek ISD",
		High_School == "CLEAR FALLS HIGH SCHOOL" ~ "Clear Creek ISD",
		High_School == "CLEAR LAKE HIGH SCHOOL" ~ "Clear Creek ISD",
		High_School == "CLEAR SPRINGS HIGH SCHOOL" ~ "Clear Creek ISD",
		High_School == "CLEAR VIEW HIGH SCHOOL" ~ "Clear Creek ISD",
		High_School == "CLEAR HORIZONS EARLY COLLEGE HIGH SCHOOL" ~ "Clear Creek ISD",
		High_School == "CLIFTON HIGH SCHOOL" ~ "Clifton ISD",
		High_School == "CLINT HIGH SCHOOL" ~ "Clint ISD",
		High_School == "CLYDE HIGH SCHOOL" ~ "Clyde Consolidated ISD",
		High_School == "COLONY HIGH SCHOOL" ~ "Lewisville ISD",
		High_School == "COMANCHE HIGH SCHOOL" ~ "Comanche ISD",
		High_School == "CONROE HIGH SCHOOL" ~ "Conroe ISD",
		High_School == "CRANDALL HIGH SCHOOL" ~ "Crandall ISD",
		High_School == "CYPRESS FALLS HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "CYPRESS CREEK HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "CYPRESS LAKES HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "CYPRESS RANCH HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "CYPRESS RIDGE HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "CYPRESS SPRINGS HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "CYPRESS SPRINGS HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "CYPRESS WOODS HIGH SCHOOL" ~ "Cypress Fairbanks ISD",
		High_School == "DEL RIO HIGH SCHOOL" ~ "San Felipe Del Rio Consolidated ISD",
		High_School == "DEL VALLE HIGH SCHOOL" ~ "Del Valle ISD",
		High_School == "DOUGLAS MACARTHUR HIGH SCHOOL" ~ "North East ISD",
		High_School == "DUBLIN HIGH SCHOOL" ~ "Dublin ISD",
		High_School == "DUMAS HIGH SCHOOL" ~ "Dumas ISD",
		High_School == "EAGLE PASS HIGH SCHOOL" ~ "Eagle Pass ISD",
		High_School == "EARL WARREN HIGH SCHOOL" ~ "Northside ISD",
		High_School == "EAST BERNARD HIGH SCHOOL" ~ "East Bernard ISD",
		High_School == "EASTWOOD HIGH SCHOOL" ~ "Ysleta ISD",
		High_School == "DENISON SENIOR HIGH SCHOOL" ~ "Denison ISD",
		High_School == "ENNIS HIGH SCHOOL" ~ "Ennis ISD",
		High_School == "ESTACADO HIGH SCHOOL" ~ "Lubbock ISD",
		High_School == "FERRIS HIGH SCHOOL" ~ "Ferris ISD",
		High_School == "FLOUR BLUFF HIGH SCHOOL" ~ "Flour Bluff ISD",
		High_School == "FORNEY HIGH SCHOOL" ~ "Forney ISD",
		High_School == "FORD HIGH SCHOOL" ~ "Quinlan ISD",
		High_School == "FORT STOCKTON HIGH SCHOOL" ~ "Fort Stockton ISD",
		High_School == "GAINESVILLE HIGH SCHOOL" ~ "Gainesville ISD",
		High_School == "GEORGETOWN HIGH SCHOOL" ~ "Georgetown ISD",
		High_School == "GILMER HIGH SCHOOL" ~ "Gilmer ISD",
		High_School == "GLADEWATER HIGH SCHOOL" ~ "Gladewater ISD",
		High_School == "GLEN ROSE HIGH SCHOOL" ~ "Glen Rose ISD",
		High_School == "GRAHAM HIGH SCHOOL" ~ "Graham ISD",
		High_School == "GRANDVIEW HIGH SCHOOL" ~ "Grandview ISD",
		High_School == "GREENVILLE HIGH SCHOOL" ~ "Greenville ISD",
		High_School == "HARKER HEIGHTS HIGH SCHOOL" ~ "Killeen ISD",
		High_School == "HARLINGEN HIGH SCHOOL" ~ "Harlingen ISD",
		High_School == "HIGHLAND PARK HIGH SCHOOL" ~ "Highland Park ISD",
		High_School == "HIRSCHI HIGH SCHOOL" ~ "Wichata Falls ISD",
		High_School == "HOMER HANNA HIGH SCHOOL" ~ "Brownsville ISD",
		High_School == "ITASCA HIGH SCHOOL" ~ "Itasca ISD",
		High_School == "J B ALEXANDER HIGH SCHOOL" ~ "United ISD",
		High_School == "J FRANK DOBIE HIGH SCHOOL" ~ "Pasadena ISD",
		High_School == "J J PEARCE HIGH SCHOOL" ~ "Richardson ISD",
		High_School == "J M HANKS HIGH SCHOOL" ~ "Ysleta ISD",
		High_School == "J W NIXON HIGH SCHOOL" ~ "Laredo ISD",
		High_School == "JACKSBORO HIGH SCHOOL" ~ "Jacksboro ISD",
		High_School == "JACKSONVILLE HIGH SCHOOL" ~ "Jacksonville ISD",
		High_School == "JAMES E TAYLOR HIGH SCHOOL" ~ "Katy ISD",
		High_School == "JAMES EARL RUDDER HS" ~ "Bryan ISD",
		TRUE ~ "zUnknown ISD"
	)






	Include_ISD = dplyr::case_when(
		ISD == 'Fort Worth ISD' ~ 1,
		ISD == 'Mansfield ISD'  ~ 1,
		ISD == 'Arlington ISD'  ~ 1,
		ISD == 'Keller ISD'  ~ 1,
		ISD == 'Grapevine Colleyville ISD'  ~ 1,
		ISD == 'Eagle Mountain Saginaw ISD'  ~ 1,
		ISD == 'Carroll ISD'  ~ 1,
		ISD == 'Hurst Euless Bedford ISD'  ~ 1,
		ISD == 'Birdville ISD'  ~ 1,
		ISD == 'Everman ISD'  ~ 1,
		ISD == 'Crowley ISD'  ~ 1,
		ISD == 'White Settlement ISD'  ~ 1,
		ISD == 'Kennedale ISD'  ~ 1,
		ISD == 'Castleberry ISD'  ~ 1,
		ISD == 'Lake Worth ISD'  ~ 1,
		ISD == 'Northwest ISD'  ~ 1,
		ISD == 'Cleburne ISD'  ~ 1,
		TRUE ~ 0
	)









	Include_ALL = dplyr::case_when(

		ISD == 'Fort Worth ISD' ~1,
		ISD == 'Mansfield ISD' ~1,
		ISD == 'Arlington ISD' ~1,
		ISD == 'Keller ISD' ~1,
		ISD == 'Grapevine Colleyville ISD' ~1,
		ISD == 'Eagle Mountain Saginaw ISD' ~1,
		ISD == 'Carroll ISD' ~1,
		ISD == 'Hurst Euless Bedford ISD' ~1,
		ISD == 'Birdville ISD' ~1,
		ISD == 'Everman ISD' ~1,
		ISD == 'Crowley ISD' ~1,
		ISD == 'White Settlement ISD' ~1,
		ISD == 'Kennedale ISD' ~1,
		ISD == 'Castleberry ISD' ~1,
		ISD == 'Lake Worth ISD' ~1,
		ISD == 'Northwest ISD' ~1,
		ISD == 'Cleburne ISD' ~1,
		High_School == 'HARMONY SCIENCE ACADEMY' ~1,
		High_School == 'NOLAN CATHOLIC HIGH SCHOOL' ~1,
		High_School == 'WINFREE ACADEMY HIGH SCHOOL' ~1,
		High_School == 'INTERNATIONAL LEADERSHIP TEXAS KELLER HS' ~1,
		High_School == 'HARMONY SCHOOL INNOVATION' ~1,
		High_School == 'FELLOWSHIP ACADEMY' ~1,
		High_School == 'IL TEXAS ARLINGTON-GRAND PRAIRIE HS' ~1,
		High_School == 'CASSATA HIGH SCHOOL' ~1,
		TRUE ~ 0
	)






	Service_Area = dplyr::case_when(
		ISD == 'Birdville ISD'  ~ 'NE',
		ISD == 'Carroll ISD'  ~ 'NE',
		ISD == 'Grapevine Colleyville ISD'  ~ 'NE',
		ISD == 'Hurst Euless Bedford ISD'  ~ 'NE',
		ISD == 'Azle ISD'  ~ 'NW',
		ISD == 'Eagle Mountain Saginaw ISD'  ~ 'NW',
		ISD == 'Fort Worth ISD' &  High_School == 'DIAMOND HILL-JARVIS HIGH SCHOOL'  ~ 'NW',
		ISD == 'Lake Worth ISD'  ~ 'NW',
		ISD == 'Keller ISD'  ~ 'NW',
		ISD == 'Northwest ISD'  ~ 'NW',
		ISD == 'White Settlement ISD'  ~ 'NW',
		ISD == 'Crowley ISD'  ~ 'SO',
		ISD == 'Everman ISD'  ~ 'SO',
		ISD == 'Fort Worth ISD' &  High_School == 'BENBROOK MIDDLE/HIGH SCHOOL'  ~ 'SO',
		ISD == 'Fort Worth ISD' &  High_School == 'DUNBAR HIGH SCHOOL'  ~ 'SO',
		ISD == 'Fort Worth ISD' &  High_School == 'O D WYATT SENIOR HIGH SCHOOL'  ~ 'SO',
		ISD == 'Fort Worth ISD' &  High_School == 'POLYTECHNIC HIGH SCHOOL'  ~ 'SO',
		ISD == 'Fort Worth ISD' &  High_School == 'SOUTH HILLS HIGH SCHOOL'  ~ 'SO',
		ISD == 'Fort Worth ISD' &  High_School == 'SOUTHWEST HIGH SCHOOL'  ~ 'SO',
		ISD == 'Fort Worth ISD' &  High_School == 'YOUNG MENS LEADERSHIP ACADEMY'  ~ 'SO',
		ISD == 'Kennedale ISD'  ~ 'SO',
		ISD == 'Arlington ISD'  ~ 'SE',
		ISD == 'Mansfield ISD'  ~ 'SE',
		ISD == 'Castleberry ISD'  ~ 'TR',
		ISD == 'Cleburne ISD'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'AMON CARTER-RIVERSIDE HIGH SCHOOL'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'ARLINGTON HEIGHTS HIGH SCHOOL'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'EASTERN HILLS HIGH SCHOOL'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'NORTH SIDE HIGH SCHOOL'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'ROBERT L PASCHAL HIGH SCHOOL'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'TRIMBLE TECHNICAL HIGH SCHOOL'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'WESTERN HILLS HIGH SCHOOL'  ~ 'TR',
		ISD == 'Fort Worth ISD' &  High_School == 'YOUNG WOMENS LEADERSHIP ACADEMY'  ~ 'TR',
		TRUE ~ NA_character_

	)




	Service_Area_with_Private_Charter = dplyr::case_when(

		ISD == 'Birdville ISD' ~ 'NE',
		ISD == 'Carroll ISD' ~ 'NE',
		ISD == 'Grapevine Colleyville ISD' ~ 'NE',
		ISD == 'Hurst Euless Bedford ISD' ~ 'NE',
		ISD == 'Azle ISD' ~ 'NW',
		ISD == 'Eagle Mountain Saginaw ISD' ~ 'NW',
		ISD == 'Fort Worth ISD' & High_School == 'DIAMOND HILL-JARVIS HIGH SCHOOL' ~ 'NW',
		ISD == 'Lake Worth ISD' ~ 'NW',
		ISD == 'Keller ISD' ~ 'NW',
		ISD == 'Northwest ISD' ~ 'NW',
		ISD == 'White Settlement ISD' ~ 'NW',
		ISD == 'Crowley ISD' ~ 'SO',
		ISD == 'Everman ISD' ~ 'SO',
		ISD == 'Fort Worth ISD' & High_School == 'BENBROOK MIDDLE/HIGH SCHOOL' ~ 'SO',
		ISD == 'Fort Worth ISD' & High_School == 'DUNBAR HIGH SCHOOL' ~ 'SO',
		ISD == 'Fort Worth ISD' & High_School == 'O D WYATT SENIOR HIGH SCHOOL' ~ 'SO',
		ISD == 'Fort Worth ISD' & High_School == 'POLYTECHNIC HIGH SCHOOL' ~ 'SO',
		ISD == 'Fort Worth ISD' & High_School == 'SOUTH HILLS HIGH SCHOOL' ~ 'SO',
		ISD == 'Fort Worth ISD' & High_School == 'SOUTHWEST HIGH SCHOOL' ~ 'SO',
		ISD == 'Fort Worth ISD' & High_School == 'YOUNG MENS LEADERSHIP ACADEMY' ~ 'SO',
		ISD == 'Kennedale ISD' ~ 'SO',
		ISD == 'Arlington ISD' ~ 'SE',
		ISD == 'Mansfield ISD' ~ 'SE',
		ISD == 'Castleberry ISD' ~ 'TR',
		ISD == 'Cleburne ISD' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'AMON CARTER-RIVERSIDE HIGH SCHOOL' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'ARLINGTON HEIGHTS HIGH SCHOOL' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'EASTERN HILLS HIGH SCHOOL' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'NORTH SIDE HIGH SCHOOL' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'ROBERT L PASCHAL HIGH SCHOOL' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'TRIMBLE TECHNICAL HIGH SCHOOL' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'WESTERN HILLS HIGH SCHOOL' ~ 'TR',
		ISD == 'Fort Worth ISD' & High_School == 'YOUNG WOMENS LEADERSHIP ACADEMY' ~ 'TR',
		High_School == 'HARMONY SCIENCE ACADEMY' ~ 'NE',
		High_School == 'NOLAN CATHOLIC HIGH SCHOOL' ~ 'NE',
		High_School == 'WINFREE ACADEMY HIGH SCHOOL' ~ 'NE',
		High_School == 'INTERNATIONAL LEADERSHIP TEXAS KELLER HS' ~ 'NW',
		High_School == 'HARMONY SCHOOL INNOVATION' ~ 'SO',
		High_School == 'FELLOWSHIP ACADEMY' ~ 'SE',
		High_School == 'IL TEXAS ARLINGTON-GRAND PRAIRIE HS' ~ 'SE',
		High_School == 'CASSATA HIGH SCHOOL' ~ 'TR',
		TRUE ~ NA_character_
	)



	res = data.frame(ISD = ISD,
									 Include_ISD = Include_ISD,
									 Include_ALL = Include_ALL,
									 Service_Area = Service_Area,
									 Service_Area_with_Private_Charter = Service_Area_with_Private_Charter
	)



	return(res)




}










